name: image_recommender

channels:
  - pytorch
  - defaults

dependencies:
  - python=3.12

  # core
  - numpy
  - pillow

  # features (conda supported only)
  - umap-learn
  - scikit-learn
  - pytorch
  - torchvision

  # visualization
  - matplotlib
  - plotly
  - dash

  # testing
  - pytest

  # packages not available via conda
  - pip
  - pip:
      - pre-commit
      - annoy