name: image_recommender

channels:
  - pytorch
  - defaults

dependencies:
  - python=3.12
  - numpy
  - pillow
  - pytest
  - annoy
  - umap-learn
  - matplotlib
  - pytorch
  - torchvision
  - umap-learn
  - pip
  - pip:
      - pre-commit
