import cProfile
import pstats
from pathlib import Path


def run_profile(output_path: Path, func, *args, **kwargs) -> tuple[Path, any]:
    """
    Profiles a function and writes stats to file.

    Inputs:
    - output_path: Path to save the pstats file
    - func: the function to profile
    - args: positional arguments to pass to the function
    - kwargs: keyword arguments to pass to the function

    Outputs:
    - output_path: Path to the pstats file generated by the profiler
    - result: the result of the function
    """
    profiler = cProfile.Profile()
    profiler.enable()

    result = func(*args, **kwargs)

    profiler.disable()

    output_path.parent.mkdir(parents=True, exist_ok=True)
    profiler.dump_stats(str(output_path))

    return output_path, result


def load_stats(stats_path: Path, top_n: int = 10) -> pstats.Stats:
    """
    Loads pstats for further processing.

    Inputs:
    - stats_path: Path to the pstats file generated by run_profile
    - top_n: number of top bottlenecks to include in the stats

    Output: pstats.Stats object with the loaded stats
    """
    stats = pstats.Stats(str(stats_path))
    stats.sort_stats("cumulative")
    stats.print_stats(top_n)
    return stats
