import base64
import io
import json
import logging
from pathlib import Path

import numpy as np
import plotly.graph_objects as go
import plotly.io as pio
from PIL import Image
from sklearn.neighbors import NearestNeighbors

from image_recommender.config import SAMPLES_DIR
from image_recommender.db.connector import get_path_by_id

pio.renderers.default = "browser"


def load_coordinates(coords_path: Path, ids_path: Path) -> tuple[np.ndarray, np.ndarray]:
    """
    Loads embedding coordinates and corresponding image IDs
    generated by the mapping pipeline.
    """
    if not coords_path.exists():
        raise FileNotFoundError(f"Coordinate file not found: {coords_path}")

    if not ids_path.exists():
        raise FileNotFoundError(f"ID file not found: {ids_path}")

    coords = np.load(coords_path)

    if ids_path.suffix == ".npy":
        ids = np.load(ids_path, allow_pickle=True)

    elif ids_path.suffix == ".json":
        with open(ids_path, encoding="utf-8") as f:
            data = json.load(f)

        if isinstance(data, list):
            ids = np.array(data)

        elif isinstance(data, dict) and "ids" in data:
            ids = np.array(data["ids"])

        elif isinstance(data, dict) and "n_points" in data:
            ids = np.arange(data["n_points"])

        else:
            raise ValueError(f"Unsupported metadata structure in {ids_path}")

    else:
        raise ValueError(f"Unsupported ID file format: {ids_path}")

    if coords.shape[0] != len(ids):
        raise ValueError("Coordinate array and ID array length mismatch!")

    if coords.shape[1] != 2:
        raise ValueError("Coordinates must have shape (N,2)")

    return coords, ids


def build_neighbor_model(coords: np.ndarray) -> NearestNeighbors:
    """
    Builds a k-nearest neighbor index for 2D coordinates.
    """
    n_neighbors = min(9, len(coords))
    nn = NearestNeighbors(n_neighbors=n_neighbors)
    nn.fit(coords)
    return nn


def show_neighbor_grid(neighbor_ids: list[int], show: bool = True) -> None:
    """
    Displays a grid of thumbnail images for given neighbor IDs.
    """
    images = []
    for img_id in neighbor_ids:
        path = resolve_image_path(img_id)
        if path is None:
            continue
        thumb = create_thumbnail(path, size=128)
        if thumb:
            images.append(thumb)

    if not images:
        logging.warning("No neighbor images available")
        return

    fig = go.Figure()
    grid_size = int(np.ceil(np.sqrt(len(images))))
    idx = 0

    for r in range(grid_size):
        for c in range(grid_size):
            if idx >= len(images):
                break
            fig.add_layout_image(
                dict(
                    source=images[idx],
                    x=c,
                    y=-r,
                    sizex=1,
                    sizey=1,
                    xref="x",
                    yref="y",
                )
            )
            idx += 1

    fig.update_layout(
        title="Nearest Neighbor Images",
        xaxis=dict(visible=False),
        yaxis=dict(visible=False),
    )

    if show:
        fig.show()


def run_embedding_explorer(
    coords_path: Path, ids_path: Path, show: bool = True, return_figure: bool = False
) -> go.Figure | None:
    """
    Launches interactive embedding explorer.
    Input:
    - coords_path (path to coordinate file)
    - ids_path (path to ID file)
    - show (whether to show the plot)
    Output: figure
    """
    coords, ids = load_coordinates(coords_path, ids_path)

    fig = go.Figure(
        go.Scattergl(
            x=coords[:, 0],
            y=coords[:, 1],
            mode="markers",
            marker=dict(size=5),
            text=build_hover_data(ids),
            hovertemplate="%{text}<extra></extra>",
        )
    )

    fig.update_layout(title="Embedding Explorer", dragmode="pan", hovermode="closest")

    if show:
        try:
            fig.show()
        except Exception:
            pass

    if return_figure:
        return fig


def build_hover_data(ids: np.ndarray) -> list[str]:
    """
    Generates simple hover text for embedding scatter plot.
    """
    hover = []

    for image_id in ids:

        path = resolve_image_path(image_id)

        if path is None:
            hover.append(f"<b>ID:</b> {image_id}<br>No image")
            continue

        thumb = create_thumbnail(path)

        hover.append(f"<b>ID:</b> {image_id}<br><img src='{thumb}' width='96'>")

    return hover


def resolve_image_path(image_id: int) -> Path | None:
    """
    Resolves image path from database or sample directory.
    """
    try:
        path = get_path_by_id(image_id)
        if path:
            p = Path(path)
            if p.exists():
                return p
    except Exception:
        pass

    sample = SAMPLES_DIR / f"{image_id}.jpg"
    if sample.exists():
        return sample

    return None


def create_thumbnail(image_path: Path | None, size: int = 96) -> str:
    """
    Creates base64 encoded thumbnail for hover preview.
    """
    if image_path is None:
        return ""

    try:
        img = Image.open(image_path)
        img.thumbnail((size, size))

        buf = io.BytesIO()
        img.save(buf, format="PNG")

        encoded = base64.b64encode(buf.getvalue()).decode()

        return f"data:image/png;base64,{encoded}"

    except Exception:
        logging.warning(f"Failed to load image: {image_path}")
        return ""
