import base64
import io
import json
import logging
from pathlib import Path

import numpy as np
import plotly.graph_objects as go
from dash import Dash, Input, Output, dcc, html
from PIL import Image
from sklearn.neighbors import NearestNeighbors

from image_recommender.config import SAMPLES_DIR
from image_recommender.db.connector import get_path_by_id


def load_coordinates(coords_path: Path, ids_path: Path) -> tuple[np.ndarray, np.ndarray]:
    """
    Loads embedding coordinates and corresponding image IDs
    generated by the mapping pipeline.
    """
    if not coords_path.exists():
        raise FileNotFoundError(f"Coordinate file not found: {coords_path}")

    if not ids_path.exists():
        raise FileNotFoundError(f"ID file not found: {ids_path}")

    coords = np.load(coords_path)

    if ids_path.suffix == ".npy":
        ids = np.load(ids_path, allow_pickle=True)

    elif ids_path.suffix == ".json":
        with open(ids_path, encoding="utf-8") as f:
            data = json.load(f)

        if isinstance(data, list):
            ids = np.array(data)

        elif isinstance(data, dict) and "ids" in data:
            ids = np.array(data["ids"])

        elif isinstance(data, dict) and "n_points" in data:
            ids = np.arange(data["n_points"])

        else:
            raise ValueError(f"Unsupported metadata structure in {ids_path}")

    else:
        raise ValueError(f"Unsupported ID file format: {ids_path}")

    if coords.shape[0] != len(ids):
        raise ValueError("Coordinate array and ID array length mismatch!")

    if coords.shape[1] != 2:
        raise ValueError("Coordinates must have shape (N,2)")

    return coords, ids


def build_neighbor_model(coords: np.ndarray, k: int) -> NearestNeighbors:
    """
    Builds a k-nearest neighbor index for 2D coordinates.
    """
    n_neighbors = min(k + 1, len(coords))
    nn = NearestNeighbors(n_neighbors=n_neighbors)
    nn.fit(coords)
    return nn


def show_neighbor_grid(neighbor_ids: list[int], db_path: Path) -> list:
    """
    Displays a grid of thumbnail images for given neighbor IDs.
    """
    images = []
    for img_id in neighbor_ids:
        path = resolve_image_path(int(img_id), db_path)

        if path is None:
            continue
        thumb = create_thumbnail(path, size=128)
        if thumb:
            images.append(
                html.Div(
                    [
                        html.Div(f"ID: {img_id}", style={"textAlign": "center"}),
                        html.Img(src=thumb, style={"width": "128px", "margin": "5px"}),
                    ]
                )
            )

    return images


def build_scatter(coords: np.ndarray, ids: np.ndarray, db_path: Path) -> go.Figure:
    """
    Creates a Plotly ScatterGL figure for 2D embeddings.
    """
    hover_data = build_hover_data(ids, db_path)

    fig = go.Figure(
        go.Scattergl(
            x=coords[:, 0],
            y=coords[:, 1],
            mode="markers",
            marker=dict(size=5, opacity=0.6),
            text=hover_data,
            hovertemplate="%{text}<extra></extra>",
        )
    )

    fig.update_layout(title="Embedding Explorer", dragmode="pan", hovermode="closest")

    return fig


def run_embedding_explorer(
    coords_path: Path,
    ids_path: Path,
    db_path: Path,
    k: int = 5,
    show: bool = True,
    return_figure: bool = False,
) -> go.Figure | None:
    """
    Launches interactive embedding explorer.
    Input:
    - coords_path (path to coordinate file)
    - ids_path (path to ID file)
    - k (number of neighbors)
    - show (whether to show the app)
    Output: figure
    """
    coords, ids = load_coordinates(coords_path, ids_path)

    nn = build_neighbor_model(coords, k)

    fig = build_scatter(coords, ids, db_path)

    app = Dash(__name__)

    app.layout = html.Div(
        [
            html.H2("Embedding Explorer"),
            dcc.Graph(
                id="scatter",
                figure=fig,
                style={"height": "70vh"},
            ),
            html.H3("Nearest Neighbors"),
            html.Div(
                id="neighbors",
                style={"display": "flex", "flexWrap": "wrap"},
            ),
        ]
    )

    @app.callback(
        Output("neighbors", "children"),
        Input("scatter", "clickData"),
    )
    def update_neighbors(clickData):
        if not clickData or "points" not in clickData:
            return html.Div("Click a point to see neighbors")

        idx = clickData["points"][0]["pointIndex"]

        _, neighbors = nn.kneighbors([coords[idx]])
        neighbor_ids = ids[neighbors[0]]

        neighbor_ids = [int(i) for i in neighbor_ids if i != ids[idx]]

        neighbor_ids = neighbor_ids[:k]

        return show_neighbor_grid(neighbor_ids, db_path)

    if show:
        app.run(debug=True)

    if return_figure:
        return fig


def build_hover_data(ids: np.ndarray, db_path: Path) -> list[str]:
    """
    Generates simple hover text for embedding scatter plot.
    """
    hover = []

    for image_id in ids:
        path = resolve_image_path(int(image_id), db_path)

        if path is None:
            hover.append(f"<b>ID:</b> {image_id}<br>No image")
            continue

        hover.append(f"<b>ID:</b> {image_id}<br>Path: {path}")

    return hover


def resolve_image_path(image_id: int, db_path: Path) -> Path | None:
    """
    Resolves image path from database or sample directory.
    """
    try:
        path = get_path_by_id(image_id, db_path)
        if path:
            p = Path(path)
            if p.exists():
                return p
    except Exception as e:
        logging.warning(f"DB lookup failed for {image_id}: {e}")

    sample = SAMPLES_DIR / f"{image_id}.jpg"
    if sample.exists():
        return sample

    return None


def create_thumbnail(image_path: Path | None, size: int = 96) -> str:
    """
    Creates base64 encoded thumbnail for hover preview.
    """
    if image_path is None:
        return ""

    try:
        with Image.open(image_path) as img:
            img.thumbnail((size, size))

            buf = io.BytesIO()
            img.save(buf, format="PNG")

        encoded = base64.b64encode(buf.getvalue()).decode()

        return f"data:image/png;base64,{encoded}"

    except Exception:
        logging.warning(f"Failed to load image: {image_path}")
        return ""
