from pathlib import Path

import numpy as np
import plotly.graph_objects as go

from image_recommender.config import SAMPLES_DIR
from image_recommender.db.connector import get_path_by_id


def load_coordinates(coords_path: Path, ids_path: Path) -> tuple[np.ndarray, np.ndarray]:
    """
    Loads embedding coordinates and corresponding image IDs
    from separate numpy files generated by the mapping pipeline.
    """
    if not coords_path.exists():
        raise FileNotFoundError(f"Coordinate file not found: {coords_path}")

    if not ids_path.exists():
        raise FileNotFoundError(f"ID file not found: {ids_path}")

    coords = np.load(coords_path)
    ids = np.load(ids_path)

    if coords.shape[0] != len(ids):
        raise ValueError("Coordinate array and ID array length mismatch!")

    if coords.shape[1] != 2:
        raise ValueError("Coordinates must have shape (N,2)")

    return coords, ids


def run_embedding_explorer(
    coords_path: Path, ids_path: Path, show: bool = True, return_figure: bool = False
) -> go.Figure | None:
    """
    Launches interactive embedding explorer.
    Input:
    - coords_path (path to coordinate file)
    - ids_path (path to ID file)
    - show (whether to show the plot)
    Output: figure
    """
    coords, ids = load_coordinates(coords_path, ids_path)

    fig = go.Figure(
        go.Scattergl(
            x=coords[:, 0],
            y=coords[:, 1],
            mode="markers",
            marker=dict(size=5),
            text=build_hover_data(ids),
            hovertemplate="%{text}<extra></extra>",
        )
    )

    fig.update_layout(title="Embedding Explorer", dragmode="pan", hovermode="closest")

    if show:
        try:
            fig.show()
        except Exception:
            pass

    if return_figure:
        return fig


def build_hover_data(ids: np.ndarray) -> list[str]:
    """
    Generates simple hover text for embedding scatter plot.
    """
    return [f"ID: {i}" for i in ids]


def resolve_image_path(image_id: int) -> Path | None:
    """
    Resolves image path from database or sample directory.
    """
    try:
        path = get_path_by_id(image_id)
        if path:
            p = Path(path)
            if p.exists():
                return p
    except Exception:
        pass

    sample = SAMPLES_DIR / f"{image_id}.jpg"
    if sample.exists():
        return sample

    return None
